inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'sms_country.gemspec'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
